name: Django CI

on:
  push:
    branches: 

    - main
    - blog-lab4

  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
       

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Update Sources
        run: sudo apt-get update
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run Tests
        env:
          DEBUG: "0"
          SECRET_KEY: CI_CD_TEST_KEY
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: djtesting
          POSTGRES_PORT: 5432
        run: |
          python manage.py test
            
